hiblup hiblup_snps_indels.r 1 1
hiblup hiblup_snps_indels.r 2 1
hiblup hiblup_snps_indels.r 3 1
hiblup hiblup_snps_indels.r 4 1
hiblup hiblup_snps_indels.r 5 1
hiblup hiblup_snps_indels.r 6 1
hiblup hiblup_snps_indels.r 7 1
hiblup hiblup_snps_indels.r 8 1
hiblup hiblup_snps_indels.r 9 1
hiblup hiblup_snps_indels.r 10 1
hiblup hiblup_snps_indels.r 11 1
hiblup hiblup_snps_indels.r 12 1
hiblup hiblup_snps_indels.r 13 1
hiblup hiblup_snps_indels.r 14 1
hiblup hiblup_snps_indels.r 15 1
hiblup hiblup_snps_indels.r 16 1
hiblup hiblup_snps_indels.r 17 1
hiblup hiblup_snps_indels.r 18 1
hiblup hiblup_snps_indels.r 19 1
hiblup hiblup_snps_indels.r 20 1
hiblup hiblup_snps_indels.r 1 2
hiblup hiblup_snps_indels.r 2 2
hiblup hiblup_snps_indels.r 3 2
hiblup hiblup_snps_indels.r 4 2
hiblup hiblup_snps_indels.r 5 2
hiblup hiblup_snps_indels.r 6 2
hiblup hiblup_snps_indels.r 7 2
hiblup hiblup_snps_indels.r 8 2
hiblup hiblup_snps_indels.r 9 2
hiblup hiblup_snps_indels.r 10 2
hiblup hiblup_snps_indels.r 11 2
hiblup hiblup_snps_indels.r 12 2
hiblup hiblup_snps_indels.r 13 2
hiblup hiblup_snps_indels.r 14 2
hiblup hiblup_snps_indels.r 15 2
hiblup hiblup_snps_indels.r 16 2
hiblup hiblup_snps_indels.r 17 2
hiblup hiblup_snps_indels.r 18 2
hiblup hiblup_snps_indels.r 19 2
hiblup hiblup_snps_indels.r 20 2
hiblup hiblup_snps_indels.r 1 3
hiblup hiblup_snps_indels.r 2 3
hiblup hiblup_snps_indels.r 3 3
hiblup hiblup_snps_indels.r 4 3
hiblup hiblup_snps_indels.r 5 3
hiblup hiblup_snps_indels.r 6 3
hiblup hiblup_snps_indels.r 7 3
hiblup hiblup_snps_indels.r 8 3
hiblup hiblup_snps_indels.r 9 3
hiblup hiblup_snps_indels.r 10 3
hiblup hiblup_snps_indels.r 11 3
hiblup hiblup_snps_indels.r 12 3
hiblup hiblup_snps_indels.r 13 3
hiblup hiblup_snps_indels.r 14 3
hiblup hiblup_snps_indels.r 15 3
hiblup hiblup_snps_indels.r 16 3
hiblup hiblup_snps_indels.r 17 3
hiblup hiblup_snps_indels.r 18 3
hiblup hiblup_snps_indels.r 19 3
hiblup hiblup_snps_indels.r 20 3
hiblup hiblup_snps_indels.r 1 4
hiblup hiblup_snps_indels.r 2 4
hiblup hiblup_snps_indels.r 3 4
hiblup hiblup_snps_indels.r 4 4
hiblup hiblup_snps_indels.r 5 4
hiblup hiblup_snps_indels.r 6 4
hiblup hiblup_snps_indels.r 7 4
hiblup hiblup_snps_indels.r 8 4
hiblup hiblup_snps_indels.r 9 4
hiblup hiblup_snps_indels.r 10 4
hiblup hiblup_snps_indels.r 11 4
hiblup hiblup_snps_indels.r 12 4
hiblup hiblup_snps_indels.r 13 4
hiblup hiblup_snps_indels.r 14 4
hiblup hiblup_snps_indels.r 15 4
hiblup hiblup_snps_indels.r 16 4
hiblup hiblup_snps_indels.r 17 4
hiblup hiblup_snps_indels.r 18 4
hiblup hiblup_snps_indels.r 19 4
hiblup hiblup_snps_indels.r 20 4
hiblup hiblup_snps_indels.r 1 5
hiblup hiblup_snps_indels.r 2 5
hiblup hiblup_snps_indels.r 3 5
hiblup hiblup_snps_indels.r 4 5
hiblup hiblup_snps_indels.r 5 5
hiblup hiblup_snps_indels.r 6 5
hiblup hiblup_snps_indels.r 7 5
hiblup hiblup_snps_indels.r 8 5
hiblup hiblup_snps_indels.r 9 5
hiblup hiblup_snps_indels.r 10 5
hiblup hiblup_snps_indels.r 11 5
hiblup hiblup_snps_indels.r 12 5
hiblup hiblup_snps_indels.r 13 5
hiblup hiblup_snps_indels.r 14 5
hiblup hiblup_snps_indels.r 15 5
hiblup hiblup_snps_indels.r 16 5
hiblup hiblup_snps_indels.r 17 5
hiblup hiblup_snps_indels.r 18 5
hiblup hiblup_snps_indels.r 19 5
hiblup hiblup_snps_indels.r 20 5
